- name: Create /home/backup/mysql directory
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    mode: '0755'
    
- name: Create a mysql user backup
  community.mysql.mysql_user:
    name: backup
    password: "{{ mysql_backup_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:SELECT,LOCK TABLES"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  notify:
    - Restart mysql

- name: Create configuration file
  ansible.builtin.template:
    src: ../templates/my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: '0755'
  no_log: true

- name: Create cron tab for creating backups
  ansible.builtin.template:
    src: ../templates/mysql-backup
    dest: /etc/cron.d/mysql-backup
