---
 - name: install nginx
   apt:
     name: nginx
     state: latest
     update_cache: yes
     
 - name: nginx config
   ansible.builtin.template:
     src: ../nginx/templates/default
     dest: /etc/nginx/sites-enabled/default
   notify:
     - Restart nginx
      
 - name: Start service nginx
   ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
