- name: Create grafana directories directory
  ansible.builtin.file:
    name: "/opt/grafana/provisioning/{{ item }}"
    state: directory
    recurse: yes
  loop:
    - dashboards
    - datasources

- name: Grafana configuration
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: yes
  notify: Restart grafana docker container

- name: Add default dashboard config
  ansible.builtin.template:
    src: ../templates/main_dashboard.yaml
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify: Restart grafana docker container

- name: Add main dashboard json file
  ansible.builtin.copy:
    src: ../files/main.json
    dest: /opt/grafana/provisioning/dashboards/
  notify: Restart grafana docker container

- name: Add mysql dashboard json file
  ansible.builtin.copy:
    src: ../files/mysql.json
    dest: /opt/grafana/provisioning/dashboards/
  notify: Restart grafana docker container

- name: Add syslog dashboard json file
  ansible.builtin.copy:
    src: ../files/syslog.json
    dest: /opt/grafana/provisioning/dashboards/
  notify: Restart grafana docker container

- name: Add datasource config
  ansible.builtin.template:
    src: ../templates/main_datasource.yaml
    dest: /opt/grafana/provisioning/datasources/default.yaml
  notify: Restart grafana docker container

- name: Grafana Docker container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: grafana
    image: grafana/grafana:8.3.3
    restart_policy: always
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
