- name: Create agama directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Download Dockerfile and agama.py files
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}
    dest: /opt/agama
  loop:
    - agama.py
    - Dockerfile

- name: Build agama docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Create two agama docker containers
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: "agama_{{ item }}"
    image: agama
    published_ports: "{{ agama_port + item|int}}:8000"
    restart_policy: always
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
  no_log: true
  with_sequence: start=0 end="{{ (nginx_container_per_vm*agama_stride)-1 }}" stride="{{ agama_stride }}"
    
    

