- name: Create a backup user
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/backup/.ssh/id_rsa.pub
    
- name: Move file with a key
  ansible.builtin.template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
