- name: Restart nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: restarted
  when: install.changed

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
