# # config file version
apiVersion: 1

 # list of datasources to insert/update depending
 # on what's available in the database
datasources:
   # <string, required> name of the datasource. Required
 - name: Prometheus
   # <string, required> datasource type. Required
   type: prometheus
   # <string, required> access mode. direct or proxy. Required
   access: proxy
   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
   # <string> url
   url: http://timnet238-2:9090/prometheus
   # <bool> mark as default datasource. Max one per org
   isDefault: true
   version: 1
   # <bool> allow users to edit datasources from the UI.
   editable: true
   
 - name: InfluxDB
   type: influxdb
   access: proxy
   url: http://timnet238-1:8086
   database: latency
   editable: true

 - name: InfluxDB-telegraf
   type: influxdb
   access: proxy
   url: http://timnet238-1:8086
   database: telegraf
   editable: true
