apiVersion: 1

datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   orgId: 1
   url: http://timnet238-2:9090/prometheus
   isDefault: true
   version: 1
   editable: true

   
 - name: InfluxDB
   type: influxdb
   access: proxy
   url: http://timnet238-1:8086
   database: latency
   editable: true

 - name: InfluxDB-telegraf
   type: influxdb
   access: proxy
   url: http://timnet238-1:8086
   database: telegraf
   editable: true
