apiVersion: 1

datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   orgId: 1
   url: http://prometheus:{{ prometheus_port }}/prometheus
   isDefault: true
   version: 1
   editable: true

 - name: InfluxDB
   type: influxdb
   access: proxy
   url: http://influxdb:8086
   database: latency
   editable: true

 - name: InfluxDB-telegraf
   type: influxdb
   access: proxy
   url: http://influxdb:8086
   database: telegraf
   editable: true
