- name: Stop and disable systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Create correct resolv.conf file
  ansible.builtin.template:
    src: ../templates/resolv.conf.j2
    dest: /etc/resolv.conf
  notify:
    - rndc reload
