- name: Restart grafana docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart: yes
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
    container_default_behavior: no_defaults
