- name: install docker package
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker

- name: Start and enable docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

