- name: Restart mysql
  ansible.builtin.service: 
    name: mysql
    state: restarted
  become: yes
  
- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host

- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    primary_host: "{{ mysql_host }}"
    primary_user: "{{ mysql_replication_user }}"
    primary_password: "{{ mysql_replication_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host
