- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted
    
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
