- name: Install bind9
  ansible.builtin.apt:
    name: bind9

- name: Configure access rules for DNS server
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify:
    - Restart bind9

- name: Configure 
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
    - Restart bind9

- name: Configure 
  ansible.builtin.template:
    src: db.clickit.io.j2
    dest: /var/lib/bind/db.clickit.io
  notify:
    - Restart bind9

