- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
    
- name: Update CA certificates
  ansible.builtin.apt:
    name: ca-certificates>=20230300*
    
- name: Create rsyslog conf file
  ansible.builtin.template:
    src: ../templates/10-telegraf.conf
    dest: /etc/rsyslog.d/10-telegraf.conf
  notify:
    - Restart rsyslog
  
- name: hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: debian
  diff: yes
